---
version: "3"

volumes:
  postgresql_data:
  registry_data:
  gateway_data:
  template_data:
  strukture_data:
  acl_data:
  konsult_data:
  kalim_data:
  nodestub_data:
  projekt_data:
  selfdata_data:
  konsent_data:

services:
  database:
    image: postgres:10.15
    environment:
      - POSTGRES_USER=rudi
      - POSTGRES_PASSWORD=rudi
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    
  registry:
    image: registry-image
    depends_on:
      - database
    ports:
      - "8761:8761"
      - "4441:4441"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4441 -Dcom.sun.management.jmxremote.rmi.port=4441 -Djava.rmi.server.hostname=registry -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      - XMX=256M
          
  gateway:
    image: gateway-image
    depends_on:
      - database
    ports:
      - "8082:8082"
      - "4442:4442"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4442 -Dcom.sun.management.jmxremote.rmi.port=4442 -Djava.rmi.server.hostname=gateway -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      - XMX=512M

  strukture:
    image: strukture-image
    depends_on:
      - database
    ports:
      - "8084:8084"
      - "4444:4444"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4444 -Dcom.sun.management.jmxremote.rmi.port=4444 -Djava.rmi.server.hostname=strukture -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

  acl:
    image: acl-image
    depends_on:
      - database
    ports:
      - "8085:8085"
      - "4445:4445"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4445 -Dcom.sun.management.jmxremote.rmi.port=4445 -Djava.rmi.server.hostname=acl -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

  kalim:
    image: kalim-image
    depends_on:
      - database
    ports:
      - "8086:8086"
      - "4446:4446"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4441 -Dcom.sun.management.jmxremote.rmi.port=4441 -Djava.rmi.server.hostname=kalim -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      
  konsult:
    image: konsult-image
    depends_on:
      - database
    ports:
      - "8087:8087"
      - "4447:4447"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4447 -Dcom.sun.management.jmxremote.rmi.port=4447 -Djava.rmi.server.hostname=konsult -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

  kos:
    image: kos-image
    depends_on:
      - database
    ports:
      - "8088:8088"
      - "4448:4448"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4448 -Dcom.sun.management.jmxremote.rmi.port=4448 -Djava.rmi.server.hostname=kos -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

  projekt:
    image: projekt-image
    depends_on:
      - database
    ports:
      - "8089:8089"
      - "4449:4449"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4449 -Dcom.sun.management.jmxremote.rmi.port=4449 -Djava.rmi.server.hostname=projekt -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

  selfdata:
    image: selfdata-image
    depends_on:
      - database
    ports:
      - "8090:8090"
      - "4450:4450"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4450 -Dcom.sun.management.jmxremote.rmi.port=4450 -Djava.rmi.server.hostname=selfdata -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

  konsent:
    image: konsent-image
    depends_on:
      - database
    ports:
      - "8091:8091"
      - "4451:4451"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=-Dcom.sun.management.jmxremote.port=4451 -Dcom.sun.management.jmxremote.rmi.port=4451 -Djava.rmi.server.hostname=konsent -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:4529
      - XMX=2G

  nodestub:
    image: nodestub-image
    ports:
      - "28001:28001"
      - "4528:4528"
    volumes:
      - ./config:/etc/rudi/config
      - ./data:/opt/rudi/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=

